# GNU Make project makefile autogenerated by Premake
ifndef config
  config=release32
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),release32)
  OBJDIR     = obj/x32/Release/App_AllBullet2Demos
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/App_AllBullet2Demos_gmake
  DEFINES   += 
  INCLUDES  += -I../../Demos3/AllBullet2Demos -I../../src -I../../btgui -I../../btgui/lua-5.2.3/src -I../../Demos3/FiniteElementMethod
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -msse2 -ffast-math -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -L../../lib -m32 -L/usr/lib32
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libBullet3AppSupport_gmake.a ../../bin/libgwen_gmake.a ../../bin/libOpenGL_Window_gmake.a ../../bin/libBulletDynamics_gmake.a ../../bin/libBulletCollision_gmake.a ../../bin/libLinearMath_gmake.a ../../bin/libBullet3Common_gmake.a ../../lib/liblua-5.2.3_gmake.a -framework OpenGL -framework Cocoa
  LDDEPS    += ../../bin/libBullet3AppSupport_gmake.a ../../bin/libgwen_gmake.a ../../bin/libOpenGL_Window_gmake.a ../../bin/libBulletDynamics_gmake.a ../../bin/libBulletCollision_gmake.a ../../bin/libLinearMath_gmake.a ../../bin/libBullet3Common_gmake.a ../../lib/liblua-5.2.3_gmake.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug32)
  OBJDIR     = obj/x32/Debug/App_AllBullet2Demos
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/App_AllBullet2Demos_gmake_debug
  DEFINES   += -D_DEBUG=1
  INCLUDES  += -I../../Demos3/AllBullet2Demos -I../../src -I../../btgui -I../../btgui/lua-5.2.3/src -I../../Demos3/FiniteElementMethod
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -ffast-math -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -L../../lib -m32 -L/usr/lib32
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libBullet3AppSupport_gmake_debug.a ../../bin/libgwen_gmake_debug.a ../../bin/libOpenGL_Window_gmake_debug.a ../../bin/libBulletDynamics_gmake_debug.a ../../bin/libBulletCollision_gmake_debug.a ../../bin/libLinearMath_gmake_debug.a ../../bin/libBullet3Common_gmake_debug.a ../../lib/liblua-5.2.3_gmake_debug.a -framework OpenGL -framework Cocoa
  LDDEPS    += ../../bin/libBullet3AppSupport_gmake_debug.a ../../bin/libgwen_gmake_debug.a ../../bin/libOpenGL_Window_gmake_debug.a ../../bin/libBulletDynamics_gmake_debug.a ../../bin/libBulletCollision_gmake_debug.a ../../bin/libLinearMath_gmake_debug.a ../../bin/libBullet3Common_gmake_debug.a ../../lib/liblua-5.2.3_gmake_debug.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release/App_AllBullet2Demos
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/App_AllBullet2Demos_gmake_x64_release
  DEFINES   += 
  INCLUDES  += -I../../Demos3/AllBullet2Demos -I../../src -I../../btgui -I../../btgui/lua-5.2.3/src -I../../Demos3/FiniteElementMethod
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -msse2 -ffast-math -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -L../../lib -m64 -L/usr/lib64
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libBullet3AppSupport_gmake_x64_release.a ../../bin/libgwen_gmake_x64_release.a ../../bin/libOpenGL_Window_gmake_x64_release.a ../../bin/libBulletDynamics_gmake_x64_release.a ../../bin/libBulletCollision_gmake_x64_release.a ../../bin/libLinearMath_gmake_x64_release.a ../../bin/libBullet3Common_gmake_x64_release.a ../../lib/liblua-5.2.3_gmake_x64_release.a -framework OpenGL -framework Cocoa
  LDDEPS    += ../../bin/libBullet3AppSupport_gmake_x64_release.a ../../bin/libgwen_gmake_x64_release.a ../../bin/libOpenGL_Window_gmake_x64_release.a ../../bin/libBulletDynamics_gmake_x64_release.a ../../bin/libBulletCollision_gmake_x64_release.a ../../bin/libLinearMath_gmake_x64_release.a ../../bin/libBullet3Common_gmake_x64_release.a ../../lib/liblua-5.2.3_gmake_x64_release.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug/App_AllBullet2Demos
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/App_AllBullet2Demos_gmake_x64_debug
  DEFINES   += -D_DEBUG=1
  INCLUDES  += -I../../Demos3/AllBullet2Demos -I../../src -I../../btgui -I../../btgui/lua-5.2.3/src -I../../Demos3/FiniteElementMethod
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -ffast-math -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -L../../lib -m64 -L/usr/lib64
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libBullet3AppSupport_gmake_x64_debug.a ../../bin/libgwen_gmake_x64_debug.a ../../bin/libOpenGL_Window_gmake_x64_debug.a ../../bin/libBulletDynamics_gmake_x64_debug.a ../../bin/libBulletCollision_gmake_x64_debug.a ../../bin/libLinearMath_gmake_x64_debug.a ../../bin/libBullet3Common_gmake_x64_debug.a ../../lib/liblua-5.2.3_gmake_x64_debug.a -framework OpenGL -framework Cocoa
  LDDEPS    += ../../bin/libBullet3AppSupport_gmake_x64_debug.a ../../bin/libgwen_gmake_x64_debug.a ../../bin/libOpenGL_Window_gmake_x64_debug.a ../../bin/libBulletDynamics_gmake_x64_debug.a ../../bin/libBulletCollision_gmake_x64_debug.a ../../bin/libLinearMath_gmake_x64_debug.a ../../bin/libBullet3Common_gmake_x64_debug.a ../../lib/liblua-5.2.3_gmake_x64_debug.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/main.o \
	$(OBJDIR)/LuaPhysicsSetup.o \
	$(OBJDIR)/TestJointTorqueSetup.o \
	$(OBJDIR)/MultiBodyVehicle.o \
	$(OBJDIR)/CoordinateFrameDemoPhysicsSetup.o \
	$(OBJDIR)/FiniteElementDemo.o \
	$(OBJDIR)/BasicDemoPhysicsSetup.o \
	$(OBJDIR)/CcdPhysicsSetup.o \
	$(OBJDIR)/SerializeSetup.o \
	$(OBJDIR)/bChunk.o \
	$(OBJDIR)/bDNA.o \
	$(OBJDIR)/bFile.o \
	$(OBJDIR)/btBulletFile.o \
	$(OBJDIR)/btBulletWorldImporter.o \
	$(OBJDIR)/btWorldImporter.o \
	$(OBJDIR)/ConstraintPhysicsSetup.o \
	$(OBJDIR)/LoadMeshFromCollada.o \
	$(OBJDIR)/ImportColladaSetup.o \
	$(OBJDIR)/ImportURDFSetup.o \
	$(OBJDIR)/ImportObjSetup.o \
	$(OBJDIR)/Wavefront2GLInstanceGraphicsShape.o \
	$(OBJDIR)/ImportSTLSetup.o \
	$(OBJDIR)/tiny_obj_loader.o \
	$(OBJDIR)/pose.o \
	$(OBJDIR)/model.o \
	$(OBJDIR)/link.o \
	$(OBJDIR)/joint.o \
	$(OBJDIR)/tinystr.o \
	$(OBJDIR)/tinyxml.o \
	$(OBJDIR)/tinyxmlerror.o \
	$(OBJDIR)/tinyxmlparser.o \
	$(OBJDIR)/printf_console.o \
	$(OBJDIR)/string_split.o \
	$(OBJDIR)/BulletMultiBodyDemos.o \
	$(OBJDIR)/MultiDofDemo.o \
	$(OBJDIR)/BasicDemo.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking App_AllBullet2Demos
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning App_AllBullet2Demos
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	-$(SILENT) cp $< $(OBJDIR)
else
	$(SILENT) xcopy /D /Y /Q "$(subst /,\,$<)" "$(subst /,\,$(OBJDIR))" 1>nul
endif
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
endif

$(OBJDIR)/main.o: ../../Demos3/AllBullet2Demos/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/LuaPhysicsSetup.o: ../../Demos3/bullet2/LuaDemo/LuaPhysicsSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/TestJointTorqueSetup.o: ../../Demos3/bullet2/MultiBodyDemo/TestJointTorqueSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MultiBodyVehicle.o: ../../Demos3/bullet2/MultiBodyDemo/MultiBodyVehicle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CoordinateFrameDemoPhysicsSetup.o: ../../Demos3/bullet2/CoordinateFrameDemo/CoordinateFrameDemoPhysicsSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/FiniteElementDemo.o: ../../Demos3/FiniteElementMethod/FiniteElementDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/BasicDemoPhysicsSetup.o: ../../Demos/BasicDemo/BasicDemoPhysicsSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/CcdPhysicsSetup.o: ../../Demos/CcdPhysicsDemo/CcdPhysicsSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/SerializeSetup.o: ../../Demos/SerializeDemo/SerializeSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/bChunk.o: ../../Extras/Serialize/BulletFileLoader/bChunk.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/bDNA.o: ../../Extras/Serialize/BulletFileLoader/bDNA.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/bFile.o: ../../Extras/Serialize/BulletFileLoader/bFile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/btBulletFile.o: ../../Extras/Serialize/BulletFileLoader/btBulletFile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/btBulletWorldImporter.o: ../../Extras/Serialize/BulletWorldImporter/btBulletWorldImporter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/btWorldImporter.o: ../../Extras/Serialize/BulletWorldImporter/btWorldImporter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ConstraintPhysicsSetup.o: ../../Demos3/bullet2/ConstraintDemo/ConstraintPhysicsSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/LoadMeshFromCollada.o: ../../Demos3/ImportColladaDemo/LoadMeshFromCollada.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ImportColladaSetup.o: ../../Demos3/ImportColladaDemo/ImportColladaSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ImportURDFSetup.o: ../../Demos3/ImportURDFDemo/ImportURDFSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ImportObjSetup.o: ../../Demos3/ImportObjDemo/ImportObjSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Wavefront2GLInstanceGraphicsShape.o: ../../Demos3/ImportObjDemo/Wavefront2GLInstanceGraphicsShape.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ImportSTLSetup.o: ../../Demos3/ImportSTLDemo/ImportSTLSetup.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/tiny_obj_loader.o: ../../Demos3/Wavefront/tiny_obj_loader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/pose.o: ../../btgui/urdf/urdfdom/urdf_parser/src/pose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/model.o: ../../btgui/urdf/urdfdom/urdf_parser/src/model.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/link.o: ../../btgui/urdf/urdfdom/urdf_parser/src/link.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/joint.o: ../../btgui/urdf/urdfdom/urdf_parser/src/joint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/tinystr.o: ../../btgui/tinyxml/tinystr.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/tinyxml.o: ../../btgui/tinyxml/tinyxml.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/tinyxmlerror.o: ../../btgui/tinyxml/tinyxmlerror.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/tinyxmlparser.o: ../../btgui/tinyxml/tinyxmlparser.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/printf_console.o: ../../btgui/urdf/boost_replacement/printf_console.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/string_split.o: ../../btgui/urdf/boost_replacement/string_split.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/BulletMultiBodyDemos.o: ../../Demos3/bullet2/FeatherstoneMultiBodyDemo/BulletMultiBodyDemos.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MultiDofDemo.o: ../../Demos3/bullet2/FeatherstoneMultiBodyDemo/MultiDofDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/BasicDemo.o: ../../Demos3/bullet2/BasicDemo/BasicDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"

-include $(OBJECTS:%.o=%.d)
