# GNU Make project makefile autogenerated by Premake
ifndef config
  config=release32
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifndef RESCOMP
  ifdef WINDRES
    RESCOMP = $(WINDRES)
  else
    RESCOMP = windres
  endif
endif

ifeq ($(config),release32)
  OBJDIR     = obj/x32/Release/App_Bullet3_OpenCL_Demos_clew
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/App_Bullet3_OpenCL_Demos_clew_gmake
  DEFINES   += -DB3_USE_CLEW
  INCLUDES  += -I../../src/clew -I../../Demos3 -I../../src -I../../btgui
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -msse2 -ffast-math -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -L../../lib -m32 -L/usr/lib32
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libBullet3AppSupport_gmake.a ../../bin/libgwen_gmake.a ../../lib/libBullet2FileLoader_gmake.a ../../lib/libBullet3OpenCL_clew_gmake.a ../../bin/libBullet3Dynamics_gmake.a ../../bin/libBullet3Collision_gmake.a ../../bin/libBullet3Geometry_gmake.a ../../bin/libBullet3Common_gmake.a -framework OpenGL -framework Cocoa
  LDDEPS    += ../../bin/libBullet3AppSupport_gmake.a ../../bin/libgwen_gmake.a ../../lib/libBullet2FileLoader_gmake.a ../../lib/libBullet3OpenCL_clew_gmake.a ../../bin/libBullet3Dynamics_gmake.a ../../bin/libBullet3Collision_gmake.a ../../bin/libBullet3Geometry_gmake.a ../../bin/libBullet3Common_gmake.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug32)
  OBJDIR     = obj/x32/Debug/App_Bullet3_OpenCL_Demos_clew
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/App_Bullet3_OpenCL_Demos_clew_gmake_debug
  DEFINES   += -D_DEBUG=1 -DB3_USE_CLEW
  INCLUDES  += -I../../src/clew -I../../Demos3 -I../../src -I../../btgui
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -ffast-math -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -L../../lib -m32 -L/usr/lib32
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libBullet3AppSupport_gmake_debug.a ../../bin/libgwen_gmake_debug.a ../../lib/libBullet2FileLoader_gmake_debug.a ../../lib/libBullet3OpenCL_clew_gmake_debug.a ../../bin/libBullet3Dynamics_gmake_debug.a ../../bin/libBullet3Collision_gmake_debug.a ../../bin/libBullet3Geometry_gmake_debug.a ../../bin/libBullet3Common_gmake_debug.a -framework OpenGL -framework Cocoa
  LDDEPS    += ../../bin/libBullet3AppSupport_gmake_debug.a ../../bin/libgwen_gmake_debug.a ../../lib/libBullet2FileLoader_gmake_debug.a ../../lib/libBullet3OpenCL_clew_gmake_debug.a ../../bin/libBullet3Dynamics_gmake_debug.a ../../bin/libBullet3Collision_gmake_debug.a ../../bin/libBullet3Geometry_gmake_debug.a ../../bin/libBullet3Common_gmake_debug.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR     = obj/x64/Release/App_Bullet3_OpenCL_Demos_clew
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/App_Bullet3_OpenCL_Demos_clew_gmake_x64_release
  DEFINES   += -DB3_USE_CLEW
  INCLUDES  += -I../../src/clew -I../../Demos3 -I../../src -I../../btgui
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -msse2 -ffast-math -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -L../../lib -m64 -L/usr/lib64
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libBullet3AppSupport_gmake_x64_release.a ../../bin/libgwen_gmake_x64_release.a ../../lib/libBullet2FileLoader_gmake_x64_release.a ../../lib/libBullet3OpenCL_clew_gmake_x64_release.a ../../bin/libBullet3Dynamics_gmake_x64_release.a ../../bin/libBullet3Collision_gmake_x64_release.a ../../bin/libBullet3Geometry_gmake_x64_release.a ../../bin/libBullet3Common_gmake_x64_release.a -framework OpenGL -framework Cocoa
  LDDEPS    += ../../bin/libBullet3AppSupport_gmake_x64_release.a ../../bin/libgwen_gmake_x64_release.a ../../lib/libBullet2FileLoader_gmake_x64_release.a ../../lib/libBullet3OpenCL_clew_gmake_x64_release.a ../../bin/libBullet3Dynamics_gmake_x64_release.a ../../bin/libBullet3Collision_gmake_x64_release.a ../../bin/libBullet3Geometry_gmake_x64_release.a ../../bin/libBullet3Common_gmake_x64_release.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = obj/x64/Debug/App_Bullet3_OpenCL_Demos_clew
  TARGETDIR  = ../../bin
  TARGET     = $(TARGETDIR)/App_Bullet3_OpenCL_Demos_clew_gmake_x64_debug
  DEFINES   += -D_DEBUG=1 -DB3_USE_CLEW
  INCLUDES  += -I../../src/clew -I../../Demos3 -I../../src -I../../btgui
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -ffast-math -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L../../bin -L../../lib -m64 -L/usr/lib64
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LIBS      += ../../bin/libBullet3AppSupport_gmake_x64_debug.a ../../bin/libgwen_gmake_x64_debug.a ../../lib/libBullet2FileLoader_gmake_x64_debug.a ../../lib/libBullet3OpenCL_clew_gmake_x64_debug.a ../../bin/libBullet3Dynamics_gmake_x64_debug.a ../../bin/libBullet3Collision_gmake_x64_debug.a ../../bin/libBullet3Geometry_gmake_x64_debug.a ../../bin/libBullet3Common_gmake_x64_debug.a -framework OpenGL -framework Cocoa
  LDDEPS    += ../../bin/libBullet3AppSupport_gmake_x64_debug.a ../../bin/libgwen_gmake_x64_debug.a ../../lib/libBullet2FileLoader_gmake_x64_debug.a ../../lib/libBullet3OpenCL_clew_gmake_x64_debug.a ../../bin/libBullet3Dynamics_gmake_x64_debug.a ../../bin/libBullet3Collision_gmake_x64_debug.a ../../bin/libBullet3Geometry_gmake_x64_debug.a ../../bin/libBullet3Common_gmake_x64_debug.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(RESOURCES) $(ARCH) $(LIBS) $(LDFLAGS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/clew.o \
	$(OBJDIR)/GpuDemo.o \
	$(OBJDIR)/main_opengl3core.o \
	$(OBJDIR)/ParticleDemo.o \
	$(OBJDIR)/PairBench.o \
	$(OBJDIR)/ConstraintsDemo.o \
	$(OBJDIR)/RaytracedShadowDemo.o \
	$(OBJDIR)/Bullet2FileDemo.o \
	$(OBJDIR)/BulletDataExtractor.o \
	$(OBJDIR)/ConcaveScene.o \
	$(OBJDIR)/GpuCompoundScene.o \
	$(OBJDIR)/GpuConvexScene.o \
	$(OBJDIR)/GpuRigidBodyDemo.o \
	$(OBJDIR)/GpuSphereScene.o \
	$(OBJDIR)/ShadowMapDemo.o \
	$(OBJDIR)/GpuSoftBodyDemo.o \
	$(OBJDIR)/tiny_obj_loader.o \
	$(OBJDIR)/GLInstancingRenderer.o \
	$(OBJDIR)/GLPrimitiveRenderer.o \
	$(OBJDIR)/LoadShader.o \
	$(OBJDIR)/TwFonts.o \
	$(OBJDIR)/GLRenderToTexture.o \
	$(OBJDIR)/fontstash.o \
	$(OBJDIR)/opengl_fontstashcallbacks.o \
	$(OBJDIR)/OpenSans.o \
	$(OBJDIR)/stb_image.o \
	$(OBJDIR)/MacOpenGLWindow.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking App_Bullet3_OpenCL_Demos_clew
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning App_Bullet3_OpenCL_Demos_clew
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	-$(SILENT) cp $< $(OBJDIR)
else
	$(SILENT) xcopy /D /Y /Q "$(subst /,\,$<)" "$(subst /,\,$(OBJDIR))" 1>nul
endif
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
endif

$(OBJDIR)/clew.o: ../../src/clew/clew.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(CFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GpuDemo.o: ../../Demos3/GpuDemos/GpuDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/main_opengl3core.o: ../../Demos3/GpuDemos/main_opengl3core.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ParticleDemo.o: ../../Demos3/GpuDemos/ParticleDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/PairBench.o: ../../Demos3/GpuDemos/broadphase/PairBench.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ConstraintsDemo.o: ../../Demos3/GpuDemos/constraints/ConstraintsDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/RaytracedShadowDemo.o: ../../Demos3/GpuDemos/raytrace/RaytracedShadowDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/Bullet2FileDemo.o: ../../Demos3/GpuDemos/rigidbody/Bullet2FileDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/BulletDataExtractor.o: ../../Demos3/GpuDemos/rigidbody/BulletDataExtractor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ConcaveScene.o: ../../Demos3/GpuDemos/rigidbody/ConcaveScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GpuCompoundScene.o: ../../Demos3/GpuDemos/rigidbody/GpuCompoundScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GpuConvexScene.o: ../../Demos3/GpuDemos/rigidbody/GpuConvexScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GpuRigidBodyDemo.o: ../../Demos3/GpuDemos/rigidbody/GpuRigidBodyDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GpuSphereScene.o: ../../Demos3/GpuDemos/rigidbody/GpuSphereScene.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/ShadowMapDemo.o: ../../Demos3/GpuDemos/shadows/ShadowMapDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GpuSoftBodyDemo.o: ../../Demos3/GpuDemos/softbody/GpuSoftBodyDemo.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/tiny_obj_loader.o: ../../Demos3/Wavefront/tiny_obj_loader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GLInstancingRenderer.o: ../../btgui/OpenGLWindow/GLInstancingRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GLPrimitiveRenderer.o: ../../btgui/OpenGLWindow/GLPrimitiveRenderer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/LoadShader.o: ../../btgui/OpenGLWindow/LoadShader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/TwFonts.o: ../../btgui/OpenGLWindow/TwFonts.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/GLRenderToTexture.o: ../../btgui/OpenGLWindow/GLRenderToTexture.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/fontstash.o: ../../btgui/OpenGLWindow/fontstash.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/opengl_fontstashcallbacks.o: ../../btgui/OpenGLWindow/opengl_fontstashcallbacks.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/OpenSans.o: ../../btgui/OpenGLWindow/OpenSans.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/stb_image.o: ../../btgui/stb_image/stb_image.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
$(OBJDIR)/MacOpenGLWindow.o: ../../btgui/OpenGLWindow/MacOpenGLWindow.mm
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"

-include $(OBJECTS:%.o=%.d)
